# Generated by Django 4.2.7 on 2023-11-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Under Review', 'Under Review'), ('Unread Yet', 'Unread Yet'), ('Read it', 'Read it'), ('Contact to you as soon as possible', 'Contact to you as soon as possible')], default='Unread Yet', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'inquiry',
                'verbose_name_plural': 'inquiries',
            },
        ),
    ]
