# Generated by Django 4.2.7 on 2023-11-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('name_slug', models.SlugField()),
                ('amount_land', models.CharField(max_length=50)),
                ('price_per_katha', models.CharField(blank=True, max_length=50)),
                ('price_total', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=50)),
                ('google_map', models.URLField(max_length=2000)),
                ('image', models.ImageField(upload_to='land/')),
                ('image_1', models.ImageField(blank=True, upload_to='land/')),
                ('image_2', models.ImageField(blank=True, upload_to='land/')),
                ('image_3', models.ImageField(blank=True, upload_to='land/')),
                ('image_4', models.ImageField(blank=True, upload_to='land/')),
                ('image_5', models.ImageField(blank=True, upload_to='land/')),
                ('purpose', models.CharField(max_length=50)),
                ('completion', models.CharField(max_length=50)),
                ('property_category', models.CharField(blank=True, max_length=50)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('short_description', models.TextField(max_length=1000)),
                ('long_description', models.TextField(max_length=2500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
            },
        ),
    ]
