# Generated by Django 4.2.7 on 2023-11-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='land',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='name_slug',
            field=models.SlugField(unique=True),
        ),
    ]
