# Generated by Django 4.2.7 on 2023-11-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('featured_title', models.TextField()),
                ('latest_title', models.TextField()),
                ('team_title', models.TextField()),
                ('service_title', models.TextField()),
                ('contact_title', models.TextField()),
                ('search_title', models.TextField()),
                ('land_poster', models.ImageField(upload_to='poster_banner/')),
                ('about_poster', models.ImageField(upload_to='poster_banner/')),
                ('service_poster', models.ImageField(upload_to='poster_banner/')),
                ('contact_poster', models.ImageField(upload_to='poster_banner/')),
                ('search_poster', models.ImageField(upload_to='poster_banner/')),
                ('login_poster', models.ImageField(upload_to='poster_banner/')),
                ('register_poster', models.ImageField(upload_to='poster_banner/')),
                ('dashboard_poster', models.ImageField(upload_to='poster_banner/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GlobalAuth',
                'verbose_name_plural': 'GlobalAuths',
            },
        ),
    ]
