# Generated by Django 4.2.7 on 2023-11-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ltdinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('addres', models.CharField(max_length=250)),
                ('facebook', models.URLField()),
                ('twiter', models.URLField(blank=True)),
                ('google', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ltdinfo',
                'verbose_name_plural': 'Ltdinfos',
            },
        ),
    ]
