# Generated by Django 4.2.7 on 2023-11-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_ltdinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltdinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
