# Generated by Django 4.2.7 on 2023-11-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_video_remove_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_video',
            name='video_url',
            field=models.TextField(),
        ),
    ]
