# Generated by Django 4.2.7 on 2023-11-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_service_image_remove_service_name_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_slug',
        ),
    ]
