# Generated by Django 4.2.7 on 2023-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('short_descripton', models.TextField(max_length=500)),
                ('long_descripton', models.TextField(max_length=2500)),
                ('image_1', models.ImageField(upload_to='about/')),
                ('image_2', models.ImageField(upload_to='about/')),
                ('image_3', models.ImageField(upload_to='about/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
    ]
